version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "localfunk"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kyx5yjg1o0yi"
s3_prefix = "localfunk"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
